var assert = require('chai').assert;
var testSuite = require("../main.js").testSuite;
var users = require("../users.js").accounts;
var stripJsonComments = require("strip-json-comments");
var fs   = require('fs');

var suiteTimeout = 10 * 60 * 1000;
var defaultOperationTimeout = 2 * 60 * 1000;

testSuite("CMTier1HomePage", suiteTimeout, {
"CMTier1HomePage": function(client, done) {
	var user = users["CM_CNA"];
	var userLook="Care Meridian";
	var d=new Date();
	var date = ("0" + (d.getMonth()+1)).slice(-2) + "/" + ("0" + d.getDate()).slice(-2) + "/" + d.getFullYear();
	var date1 = ("0" + (d.getMonth()+1)).slice(-2) + ("0" + d.getDate()).slice(-2) + d.getFullYear();
	var time = ("0" + d.getHours()).slice(-2) + ":" + ("0" + d.getMinutes()).slice(-2);
	return client
		.execUtil("convert_referral", {operatingGroup: "Care Meridian",flavor: "CA" })
		.waitForVisible("input[value='Attach File']", defaultOperationTimeout)
		.click("input[value='Edit Person Being Served']")
		.waitForVisible("input[value='Attach File']", defaultOperationTimeout)
		.getOutputTextFromInput("First Name")
		.getValue("input[id$=FirstNameInput]")
		.then(function(FName) {
			userLook=FName;
		})
		.click("img[class='unstickPbs']")
		.scroll("input[value='Add Diagnosis']")
		.click("a*=Admission 1 - ")	  
		.waitForVisible("input[value='Attach File']", defaultOperationTimeout)
		.scroll("a*=C. CA - SA1 - ")
		.click("a*=C. CA - SA1 - ")
		.waitForVisible("input[value='Attach File']", defaultOperationTimeout)
		.click("img[class='unstickPbs']")
		.scroll("input[value='Associate Diagnosis']")
		.click("input[value='New Plan']")
		.waitForVisible("input[value='Save']", defaultOperationTimeout)
		.fillInputText("Effective Date","1/12/2016")
		.fillInputText("Target Date","1/14/2017")
		.setValue("textarea[id$=txtaoe]", "Testing")
		.selectByValue("select[id$=stat1]", "New")
		.setValue("input[id$=effe1]","1/12/2016")
		.setValue("input[id$=tar1]","1/14/2016")
		.selectByValue("select[id$=stat2]", "New")
		.setValue("input[id$=start1]","1/12/2016")
		.setValue("input[id$=end1]","1/14/2016")
		.selectByValue("select[id$=type1]", "Behavior - Duration")
		.setValue("div[id$=theAction] textarea", "Testing1")
		.click("img[class='unstickPbs']")
		.scroll("input[value='Save']")
		.click("input[value='Save']")
		.waitForVisible("input[value='Finalize']", defaultOperationTimeout)
		.click("input[value='Finalize']")	

		.logInAs(user)
		.then(function () {
			return client.setValue("input[id$=PbsSearchFirstName]", userLook)
		})
		.click("input[value=Find]")
		.switchToNextWindow()
		.waitForVisible("input[value='Done']", defaultOperationTimeout)
		.setValue("input[type='search']","Served")
		.click("a*=CA, Care Meridian")
		.waitForActionStatusDisappearance("pageProcessing" , defaultOperationTimeout)
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(1) a")	
		.click("a=Add Narrative Shift Note")
		.waitForVisible("input[value=E-sign]", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.waitForVisible("input[value='Add Task']", defaultOperationTimeout)	
		.selectByVisibleText("select[class=actionList]","Create New CNA Workbook")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(5) input")
		.waitForVisible("div[aria-labelledby$='shiftDocModal'] input[value='Save']", defaultOperationTimeout)
		.setValue("input[id=shiftStartDate2]",date+" "+"01:01\t")
		.setValue("input[id=shiftEndDate2]",date+" "+time+"\t")
		.click("div[aria-labelledby$='shiftDocModal'] input[value='Save']")
		.waitForVisible("div[aria-labelledby$='shiftDocModal'] input[value='Cancel']",defaultOperationTimeout,true)
		.url("https://c.cs4.visual.force.com/apex/Home")
		//CNA Activity Logs
		.selectByVisibleText("select[id$=navigationList]","Action Plan")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("input[value='Acknowledgment Overview']", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Admission")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Admission Documents", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Admission Packet")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("input[type='search']", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Allergy")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Allergy", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Annual Health and Wellness Checklist")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Annual Health and Wellness Checklist", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Assistive Devices")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Assistive Device", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Authorizations")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Case Management Notes", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Case Management Notes")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("input[value='New Note']", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Diagnosis")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("input[value='Associate Diagnosis']", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Immunization")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Immunization - Adult", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Isolation Events")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Isolation Event", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Narrative Shift Notes")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Case Management Notes", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Nurses Shift Documentation")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Nurses Shift Documentation", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Resident Assessment")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Resident Assessment", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Restraint Events")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("input[value='Restraint Reduction Report']", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Seizures")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("input[value='Add Seizure']", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Service Assignment")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Service Assignment", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Summaries")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("input[value='New Action Plan Summary']", defaultOperationTimeout)
		.url("https://c.cs4.visual.force.com/apex/Home")
		.selectByVisibleText("select[id$=navigationList]","Therapy")
		.click("table[id$=serviceAssignmentTable] tbody tr:nth-child(1) td:nth-child(6) input")
		.waitForVisible("h3=Therapy", defaultOperationTimeout)

	}
});
